drawwritesite/drawwrite/urls.py
"""The URL mappings for DrawWrite."""

from django.conf.urls import url

from . import views

app_name = "drawwrite" #pylint: disable=invalid-name
urlpatterns = [ #pylint: disable=invalid-name
    url(r'^$', views.index, name='index'),
    url(r'^join$', views.join_game, name='joinGame'),
    url(r'^create$', views.create_game, name='createGame'),
    url(r'^play/(?P<player_id>[0-9]+)$', views.play, name='play'),
    url(r'^ajax/checkGameStart/(?P<player_id>[0-9]+)$',
        views.check_game_start, name='checkGameStart'),
    url(r'^startGame/(?P<player_id>[0-9]+)$', views.start_game,
        name='startGame'),
    url(r'^createLink/(?P<player_id>[0-9]+)$', views.create_link,
        name='createLink'),
    url(r'^checkRoundDone/(?P<player_id>[0-9]+)$', views.check_round_done,
        name='checkRoundDone'),
    url(r'^checkGameDone/(?P<game_id>[0-9]+)$', views.check_game_done,
        name='checkGameDone'),
    url(r'^showGame/(?P<game_id>[0-9]+)$', views.show_game,
        name='showGame'),
    url(r'^showChain/(?P<player_id>[0-9]+)$', views.show_chain,
        name='showChain'),
    url(r'^getAvailableGames$', views.get_available_games,
        name='getAvailableGames')
]

drawwritesite/drawwrite/models.py
"""All the models used by DrawWrite."""

from django.db import models
from django.utils import timezone

class Game(models.Model):
    """
    Games have a number of players, a unique name, and a
    created time.
    """
    name = models.CharField('Name', max_length=50)
    num_players = models.SmallIntegerField('Number of Players', default=0)
    started = models.BooleanField('Started?', default=False)
    time_created = models.DateTimeField('Time Created', default=timezone.now)
    round_num = models.SmallIntegerField('Current Round', default=0)
    num_finished_current_round = models.SmallIntegerField(
        'Number of players who have finished the current round',
        default=0
    )

    def __str__(self):
        return self.name

class Player(models.Model):
    """
    Holds information about a user, such as their name, a reference
    to their game, and their position in the cycle.
    """
    name = models.CharField('Name', max_length=50)
    game = models.ForeignKey(Game)
    position = models.SmallIntegerField('Position')
    was_creator = models.BooleanField('Created game')
    current_round = models.SmallIntegerField('Current Round', default=0)

    def __str__(self):
        return self.name

class Chain(models.Model):
    """
    A Chain is used to connect WriteLinks and DrawLinks. It keeps track
    of how many links it has, and who created it.
    """
    time_created = models.DateTimeField('Time Created', default=timezone.now)
    next_link_position = models.SmallIntegerField('Next Link Position', default=0)
    player = models.OneToOneField(Player)

    def __str__(self):
        return '{0}\'s chain'.format(self.player)

class DrawLink(models.Model):
    """
    A DrawLink holds data for a single 'draw' step of a DrawWrite game.
    """
    drawing = models.FileField('File')
    link_position = models.SmallIntegerField('Link Position')
    chain = models.ForeignKey(Chain)
    added_by = models.ForeignKey(Player)

class WriteLink(models.Model):
    """
    A WriteLink holds data for a single 'write' step of a DrawWrite game.
    """
    text = models.TextField('Description')
    link_position = models.SmallIntegerField('Link Position')
    chain = models.ForeignKey(Chain)
    added_by = models.ForeignKey(Player)

drawwritesite/drawwrite/forms.py
"""The forms used by DrawWrite."""

import logging

from django import forms
from django.core.validators import validate_slug

from drawwrite.models import Game

LOG = logging.getLogger(__name__)

class CreateGameForm(forms.Form):
    """
    Allows the user to create a game with whatever name they want.
    """
    username = forms.CharField(label='Your Name', max_length=50,
                               validators=[validate_slug])
    gamename = forms.CharField(label='Game Name', max_length=50,
                               validators=[validate_slug])


class JoinGameForm(forms.Form):
    """
    Allows the user to join a game by inputing their name and selecing a
    game name from a dropdown.
    """
    username = forms.CharField(label='Your Name', max_length=50,
                               validators=[validate_slug])
    
    def __init__(self, *args, **kwargs):
        """
        Grab the list of avaliable games to join and set the picklist to include
        all of them.
        """
        super(JoinGameForm, self).__init__(*args, **kwargs)
        self.fields['gamename'] = forms.ChoiceField(
            label='Available Games',
            choices=get_available_games,
            validators=[validate_slug],
            required=True,
        )

def get_available_games():
    """Get a list of games that are available to join."""
    games = Game.objects.filter(started=False) #pylint: disable=no-member
    if len(games) == 0:
        options = [('', '- None -')]
    else:
        options = [('', '- Select -')]
    for game in games:
        options.append((game.name, game.name))
    return options

drawwritesite/drawwrite/views.py
"""All the views for DrawWrite."""

# Imports {{{
import logging

from base64 import b64decode

from itertools import zip_longest

from django.core.files.base import ContentFile
from django.db import IntegrityError
from django.http import HttpResponseBadRequest, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import redirect, render

from drawwrite.forms import CreateGameForm, JoinGameForm
from drawwrite.models import Chain, Game, DrawLink, Player, WriteLink

from . import services
from .bracefmt import BraceFormatter as __
# }}}

LOG = logging.getLogger(__name__)

# index {{{
def index(request):
    """
    The front page of the app.
    """
    LOG.debug("enter index")

    # Create the two forms that we'll put on this page.
    create_form = CreateGameForm()
    join_form = JoinGameForm()

    # TODO errors shouldn't get added by title and description, but by number.
    #      Then I should look up the title and description from that number.
    return render(request, 'drawwrite/index.html', {
        'create_form': create_form,
        'join_form': join_form,
        'error_title': request.session.pop('error_title', None),
        'error_description': request.session.pop('error_description', None),
    })
# }}}

# join_game {{{
def join_game(request):
    """
    Proccess data that a user sends when they want to join a game.
    """
    LOG.debug('enter')

    # Send all non-POSTs to the index.
    if request.method != 'POST':
        LOG.info(__('attempted non-supported method {0}', request.method))
        request.session['error_title'] = 'Unsupported method'
        request.session['error_description'] = (
            'You\'re not allowed to send {0} requests to that endpoint.'.format(request.method),
        )
        return redirect('drawwrite:index')

    # Get the form from the POSTed data.
    form = JoinGameForm(request.POST)

    # Invalid forms redirect to the index with an error.
    if not form.is_valid():
        LOG.debug(__(
            'name {0} or gamename {1} invalid',
            form.data['username'],
            form.data['gamename'],
        ))
        request.session['error_title'] = 'Invalid input'
        request.session['error_description'] = ' '.join((
            'Your Name and the Game Name must only contain letters, numbers,',
            'underscores, and hyphens.',
        ))
        return redirect('drawwrite:index')

    # Valid forms are processed.
    gamename = form.cleaned_data['gamename']
    username = form.cleaned_data['username']

    # Get the game. On error, add error objects to the session and redirect
    # to index.
    # TODO extract this, possibly to services.py
    games = Game.objects.filter( #pylint: disable=no-member
        name=gamename,
    ).filter(
        started=False,
    )
    if len(games) > 1:
        LOG.error(__('somehow, two games with name {0} are being created', gamename))
        request.session['error_title'] = 'Non-unique game name'
        request.session['error_description'] = 'Could not find a unique game for you to join'
        return redirect('drawwrite:index')
    if len(games) < 1:
        LOG.error(__('tried to join non-existant game {0}', gamename))
        request.session['error_title'] = 'Non-existent game'
        request.session['error_description'] = ' '.join((
            'The game that you attempted to join, {0},'.format(gamename),
            'does not exist. Please check that you entered it correctly.',
        ))
        return redirect('drawwrite:index')
    game = games[0]
    LOG.debug(__('got game for player {0}', username))

    # Add a player to the game. On error, add error objects to the session and
    # redirect to index.
    player = None
    try:
        player = services.new_player(game, username, False)
    except services.GameAlreadyStarted:
        LOG.debug(__('could not add {0} to game {1}', username, game.name))
        request.session['error_title'] = 'Game started'
        request.session['error_description'] = ' '.join((
            'The game that you attempted to join has already started. Please',
            'either join a different game or start your own game.',
        ))
        return redirect('drawwrite:index')
    # TODO don't assume that all IntegrityError's mean that the game name is
    #   already taken. There are plenty of other explanations that I'm
    #   silencing by doing this.
    except IntegrityError:
        LOG.exception(__(
            'player with {0} already exists in game {1}',
            username,
            gamename,
        ))
        request.session['error_title'] = 'Player exists'
        request.session['error_description'] = ' '.join((
            'The player name that you entered is already in use in the game',
            'that you are trying to join. Please choose a new player name',
            'and try again.',
        ))
        return redirect('drawwrite:index')

    # Redirect to that game's page.
    LOG.debug('exiting join game view')
    return redirect('drawwrite:play', player.pk)
# }}}

# create_game {{{
def create_game(request):
    """
    Create a game according to the values the user specified in the form.
    """
    LOG.debug('entering create game view')

    # Send all non-POSTs to the index.
    if request.method != 'POST':
        LOG.debug(__('attempted non-supported method {0}', request.method))
        return redirect('drawwrite:index')

    # Get the form from the POSTed data.
    form = CreateGameForm(request.POST)

    # Invalid forms redirect to the index with an error.
    if not form.is_valid():
        #LOG.debug(__(
        #    'username {0} or gamename {1} invalid',
        #    form.data['username'],
        #    form.data['gamename'],
        #))
        LOG.debug(__(
            'form error: {0}',
            form.errors,
        ))
        request.session['error_title'] = 'Invalid input'
        request.session['error_description'] = ' '.join((
            'Your Name and the Game Name must only contain letters, numbers,',
            'underscores, and hyphens.',
        ))
        return redirect('drawwrite:index')

    # Valid forms are processed.
    gamename = form.cleaned_data['gamename']
    username = form.cleaned_data['username']

    # Create game. On error, add error objects to the session and redirect
    # to index.
    # TODO handle other errors that could happen?
    game = services.new_game(gamename)
    if game is None:
        request.session['error_title'] = 'Game being created'
        request.session['error_description'] = (
            'The game you are trying to join, {0}, is already being created'
        ).format(gamename)

    # Create a player for that game. On error, add error objects to the
    # session and redirect to index.
    player = None
    try:
        player = services.new_player(game, username, True)
    # TODO don't assume that all IntegrityError's mean that the user name is
    #   already taken. There are plenty of other explanations that I'm
    #   silencing by doing this.
    except services.NameTaken as exception:
        LOG.error('player name already taken')
        request.session['error_title'] = 'Player name taken'
        request.session['error_description'] = exception.message()
        return redirect('drawwrite:index')
    except IntegrityError:
        LOG.error(__('a new game has an invalid player {0}', username))
        request.session['error_title'] = 'Player name taken'
        request.session['error_description'] = ' '.join((
            'The player name that you entered, {0},'.format(username),
            ' is already taken for the game that you entered. Please',
            'try a different one.',
        ))
        return redirect('drawwrite:index')

    # Redirect to that game's page.
    LOG.debug('exiting create game view')
    return redirect('drawwrite:play', player.pk)
# }}}

# play {{{
def play(request, player_id):
    """
    The page on which players play the game.
    """
    LOG.debug('enter play view')

    # Get their player from the database using the id in the path. On error,
    # set error session attributes and redirect to index.
    player = None
    try:
        player = Player.objects.get(pk=player_id) #pylint: disable=no-member
    except Player.DoesNotExist: #pylint: disable=no-member
        LOG.error(__('non-existant player attempt: {0}', player_id))
        request.session['error_title'] = 'Player Does Not Exist'
        request.session['error_description'] = ' '.join((
            'You attempted to access a non-existant player. Plase do not',
            'do that.',
        ))
        return redirect('drawwrite:index')
    LOG.debug(__('successfully retreived player {0}', player_id))

    # Get the game from the player object.
    game = player.game
    LOG.debug(__('successfully retreived game for player {0}', player_id))

    # If the game hasn't started, show the player the waiting screen.
    if not game.started:
        LOG.debug(__('game for player {0} has not started', player_id))

        # Get a list of all players in this game.
        all_players = Player.objects.filter(game=game) #pylint: disable=no-member
        LOG.debug(__('got players in game with player {0}', player_id))

        # Get the creator of the game.
        creator = None
        for player in all_players:
            if player.was_creator:
                creator = player
        LOG.debug(__('creator of game is {0}', creator.name))

        # Render the waiting screen with all of those players.
        LOG.debug(__('showing player {0} the waiting screen', player_id))
        return render(request, 'drawwrite/waiting.html', {
            'all_players' : all_players,
            'player_id' : player_id,
            'created' : player.was_creator,
            'creator' : creator,
        })
    LOG.debug(__('game for player {0} has started', player_id))

    # The game has started. Check if it's also finished.

drawwritesite/drawwrite/templates/drawwrite/chain.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>View Chain</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico">

        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/page/chain.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/shared.css' %}">

        <script type="text/javascript" src="{% static 'drawwrite/js/jquery/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/shared.js' %}"></script>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="mainCol col-xs-12 col-sm-6 col-sm-offset-3">
                    <h3 class="text-center">{{ player.name }}</h3>
                    {% for link in links %}
                        <div>
                            {% if link.drawing %}
                                <h4>{{ link.added_by.name }} drew:</h4>
                            {% elif link.text %}
                                <h4>{{ link.added_by.name }} wrote:</h4>
                            {% endif %}
                            {% if link.drawing %}
                                <div class="indented">
                                    <img class="boxed scaleImage" src="{{ link.drawing.url }}">
                                </div>
                            {% elif link.text %}
                                <div class="indented">
                                    <p>{{ link.text }}</p>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="topSpace">
                        <a href="{% url 'drawwrite:showGame' player.game.pk %}">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </body>

</html>

drawwritesite/drawwrite/templates/drawwrite/game.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Completed Game</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico">

        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/page/game.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/shared.css' %}">

        <script type="text/javascript" src="{% static 'drawwrite/js/jquery/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/shared.js' %}"></script>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="mainCol col-xs-12 col-sm-6 col-sm-offset-3">
                    <h3 class="text-center">{{ game_name }}</h3>
                    <h4>Chains</h4>
                    {% for player in players %}
                        <div class="indented">
                            <a href="{% url 'drawwrite:showChain' player.pk %}">{{ player.name }}</a>
                        </div>
                    {% endfor %}
                    <div class="topSpace">
                        <a href="{% url 'drawwrite:index' %}">Play again?</a>
                    </div>
                </div>
            </div>
        </div>
    </body>

</html>

drawwritesite/drawwrite/templates/drawwrite/gameWaiting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Waiting Area</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico">

        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/page/gameWaiting.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/shared.css' %}">

        <script type="text/javascript" src="{% static 'drawwrite/js/jquery/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/page/gameWaiting.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/shared.js' %}"></script>

        <script type="text/javascript">var drawwriteAjaxUrl = "{% url 'drawwrite:checkGameDone' game_id %}";</script>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="mainCol col-xs-12 col-sm-6 col-sm-offset-3">
                    <h3 class="text-center">Waiting Area</h3>
                    <h4>Waiting for:</h4>
                    <div class="stillPlayingWrapper"></div>
                </div>
            </div>
        </div>
    </body>

</html>

drawwritesite/drawwrite/templates/drawwrite/index.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>DrawWrite</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico">

        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/shared.css' %}">

        <script type="text/javascript" src="{% static 'drawwrite/js/jquery/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/bootstrap/bootstrap.min.js' %}"></script>

        <script type="text/javascript">var refreshAvailableAjaxUrl = "{% url 'drawwrite:getAvailableGames' %}";</script>
        <script type="text/javascript" src="{% static 'drawwrite/js/page/index.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/shared.js' %}"></script>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="mainCol col-xs-12 col-sm-6 col-sm-offset-3">
                    <h1 class="text-center">DrawWrite!</h1>

                    {% if error_title %}
                        <div class="panel panel-danger">
                            <div class="panel-heading">
                                <h2 class="panel-title">{{error_title}}</h2>
                            </div>
                            <div class="panel-body">
                                <p>{{error_description}}</p>
                            </div>
                        </div>
                    {% endif %}

                    <div>

                        <!-- Navigation tabs to choose 'creation' or 'joining' -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active"><a href="#create" aria-controls="create" role="tab" data-toggle="tab">Create</a></li>
                            <li role="presentation"><a href="#join" aria-controls="join" role="tab" data-toggle="tab">Join</a></li>
                        </ul>

                        <!-- Tab panes -->
                        <div class="tab-content">

                            <!-- Create tab -->
                            <div role="tabpanel" class="tab-pane active" id="create">
                                <form method="post" action="{% url 'drawwrite:createGame' %}">

                                    {% csrf_token %}

                                    <div class="form-group">
                                        <label for="{{ create_form.username.id_for_label }}">Your name:</label>
                                        {{ create_form.username|add_class:"form-control" }}
                                    </div>

                                    <div class="form-group game-name">
                                        <label for="{{ create_form.gamename.id_for_label }}">Game name:</label>
                                        {{ create_form.gamename|add_class:"form-control" }}
                                    </div>

                                    <button type="submit" class="btn btn-default col-xs-12 col-sm-6">Create</button>

                                </form>
                            </div>

                            <!-- Join tab -->
                            <div role="tabpanel" class="tab-pane" id="join">
                                <form method="post" action="{% url 'drawwrite:joinGame' %}">

                                    {% csrf_token %}

                                    <div class="form-group">
                                        <label for="{{ join_form.username.id_for_label }}">Your name:</label>
                                        {{ join_form.username|add_class:"form-control" }}
                                    </div>

                                    <div class="form-group">
                                        <label for="{{ join_form.gamename.id_for_label }}">Available games:</label>
                                        {{ join_form.gamename|add_class:"form-control" }}
                                        <a class="refresh-available" href="{% url 'drawwrite:getAvailableGames' %}">Refresh List</a>
                                    </div>

                                    <button type="submit" class="btn btn-default col-xs-12 col-sm-6">Join</button>

                                </form>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </body>

</html>

drawwritesite/drawwrite/templates/drawwrite/roundWaiting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Waiting Area</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico">

        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/page/roundWaiting.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/shared.css' %}">

        <script type="text/javascript" src="{% static 'drawwrite/js/jquery/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/page/roundWaiting.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/shared.js' %}"></script>

        <script type="text/javascript">var drawwriteAjaxUrl = "{% url 'drawwrite:checkRoundDone' player_id %}";</script>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="mainCol col-xs-12 col-sm-6 col-sm-offset-3">
                    <h3 class="text-center">Waiting Area</h3>
                    <h4>Waiting for:</h4>
                    <div class="stillPlayingWrapper"></div>
                </div>
            </div>
        </div>
    </body>

</html>

drawwritesite/drawwrite/templates/drawwrite/waiting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <title>Waiting Area</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/x-icon" href="/favicon/favicon.ico">

        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/page/waiting.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'drawwrite/css/shared.css' %}">

        <script type="text/javascript" src="{% static 'drawwrite/js/jquery/jquery-3.2.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/page/waiting.js' %}"></script>
        <script type="text/javascript" src="{% static 'drawwrite/js/shared.js' %}"></script>

        <script type="text/javascript">var drawwriteAjaxUrl = "{% url 'drawwrite:checkGameStart' player_id %}";</script>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="mainCol col-xs-12 col-sm-6 col-sm-offset-3">
                    <h3 class="text-center">Lobby</h3>

                    <h4>Players:</h4>
                    <div id="nameList">
                        {% for player in all_players %}
                            <div class="indented">
                                {{ player.name }}
                            </div>
                        {% endfor %}
                    </div>

                    {% if created == True %}
                        <form action="{% url 'drawwrite:startGame' player_id %}" method="POST">
                            {% csrf_token %}
                            <div class="topSpace">
                                <button class="btn btn-default col-xs-12 col-sm-4 col-md-3">Start Game</button>
                            </div>
                        </form>
                    {% else %}
                        <p class="topSpace">Once all players have joined, <strong>{{ creator }}</strong> will start the game!</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </body>

</html>